use_frameworks!
platform:ios, 12.0
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

target 'CCRegionSelector_Example' do
  pod 'CCRegionSelector', :path => '../', :testspecs => ['Tests']

  target 'CCRegionSelector_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
